import { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Issue = { type: string; severity: string; confidence: number };
type Analysis = { id?: number; filename: string; quality_score: number; quality_label: string; issues: Issue[]; statistics: Record<string, number>; explanation: string; model_version: string; created_at?: string };
const API = (import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000').replace(/\/+$/, '');

function App() {
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState('');
  const [result, setResult] = useState<Analysis | null>(null); const [history, setHistory] = useState<Analysis[]>([]);
  const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const scoreClass = useMemo(() => result ? (result.quality_score >= 80 ? 'good' : result.quality_score >= 50 ? 'warn' : 'bad') : '', [result]);
  useEffect(() => { fetch(`${API}/api/analyses`).then(r => r.ok ? r.json() : []).then(setHistory).catch(() => setError('Unable to reach backend API. If recently deployed or sleeping, please wait a moment and refresh.')); }, []);
  function choose(selected: File | undefined) { if (!selected) return; setFile(selected); setPreview(URL.createObjectURL(selected)); setResult(null); setError(''); }
  async function analyse() { if (!file) return; setLoading(true); setError(''); const form = new FormData(); form.append('file', file); try { const res = await fetch(`${API}/api/analyses`, { method: 'POST', body: form }); const body = await res.json(); if (!res.ok) throw new Error(body.detail || 'Analysis failed'); setResult(body); setHistory(items => [body, ...items]); } catch (err) { setError(err instanceof Error ? err.message : 'Analysis failed'); } finally { setLoading(false); } }
  return <main><header><div><p className="eyebrow">AI-POWERED VISUAL INSPECTION</p><h1>VisionCheck</h1></div><span className="status">● API-backed quality analysis</span></header>
    <section className="hero"><div><p className="eyebrow">IMAGE QUALITY & DEFECT DETECTION</p><h2>Know whether an image is fit for use.</h2><p>Upload an image to detect blur, exposure problems, noise, and potential visual defects with an interpretable machine-learning model.</p></div><div className="method"><b>How it decides</b><span>11 visual features</span><span>Multi-label Random Forest</span><span>Confidence-based score</span></div></section>
    <section className="grid"><div className="card uploader"><h3>1. Upload an image</h3><label className="drop"><input type="file" accept="image/jpeg,image/png,image/webp,image/bmp" onChange={e => choose(e.target.files?.[0])}/>{preview ? <img src={preview} alt="Selected upload"/> : <><strong>Drop an image here</strong><span>JPEG, PNG, WEBP, or BMP · 10 MB maximum</span></>}</label>{file && <div className="file-row"><span>{file.name}</span><button onClick={analyse} disabled={loading}>{loading ? 'Analysing…' : 'Analyse image'}</button></div>}{error && <p className="error">{error}</p>}</div>
      <div className="card result"><h3>2. Quality assessment</h3>{result ? <><div className={`score ${scoreClass}`}><strong>{result.quality_score}</strong><span>/100</span><b>{result.quality_label.replace('_', ' ')}</b></div><p className="explanation">{result.explanation}</p><div className="issues">{result.issues.length ? result.issues.map(issue => <div className="issue" key={issue.type}><span>{issue.type}</span><em className={issue.severity}>{issue.severity}</em><b>{Math.round(issue.confidence * 100)}%</b></div>) : <p>No issue crossed the reporting threshold.</p>}</div><details><summary>Feature statistics</summary><div className="stats">{Object.entries(result.statistics).map(([k,v]) => <span key={k}>{k.replace(/_/g,' ')} <b>{v.toFixed(2)}</b></span>)}</div></details></> : <div className="empty">Your score, detected issues, confidence, and visual statistics will appear here.</div>}</div></section>
    <section className="card history"><div className="section-title"><div><p className="eyebrow">PERSISTED RESULTS</p><h3>Analysis history</h3></div><span>{history.length} saved</span></div>{history.length ? <div className="history-list">{history.map(item => <button key={item.id} className="history-item" onClick={() => setResult(item)}><span>{item.filename}</span><b className={item.quality_score >= 80 ? 'good' : item.quality_score >= 50 ? 'warn' : 'bad'}>{item.quality_score}</b><em>{item.quality_label.replace('_',' ')}</em><small>{item.created_at ? new Date(item.created_at).toLocaleString() : 'Just now'}</small></button>)}</div> : <p className="empty">No saved analyses yet.</p>}</section>
    <footer>Local-first · No external AI or vision APIs · Model version shown with every result</footer></main>
}
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
